services:
  database:
    image: mysql:8.0
    container_name: mygit_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MyGitDB
    ports:
      - "3306:3306"
    volumes:
      - mygit_db_data:/var/lib/mysql
      - ./db/MyGitDB.sql:/docker-entrypoint-initdb.d/MyGitDB.sql

  backend:
    build:
      context: ./core/app
      dockerfile: DockerFile
    container_name: mygit_core
    env_file:
      - ./core/.env
    ports:
      - "8000:8000"
    volumes:
      - ./core/app:/app
    depends_on:
      - database

volumes:
  mygit_db_data: